ic_uber/interface/ic_uber/interface/juris/urls.py
from django.urls import path, include
from . import views 
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
import juris.views
from django.conf import settings
import os
from django.conf.urls import  url

# https://docs.djangoproject.com/en/3.0/topics/http/urls/
app_name = 'juris'

urlpatterns = [

    path('', views.MainView.as_view(), name='all'),
    #path('accounts/', views.MyView.as_view(), name='login'),
    path('protect', views.ProtectView.as_view(), name='protect'),
    path('python', views.DumpPython.as_view(), name='python'),

    path('empresa/', views.EmpresaView.as_view(), name='empresa_list'),
    path('empresa/create/', views.EmpresaCreate.as_view(), name='empresa_create'),
    path('empresa/<int:pk>/update/', views.EmpresaUpdate.as_view(), name='empresa_update'),
    path('empresa/<int:pk>/delete/', views.EmpresaDelete.as_view(), name='empresa_delete'),

    path('busca/', views.TermoBuscaView.as_view(), name='busca_list'),
    path('busca/create/', views.TermoBuscaCreate.as_view(), name='busca_create'),
    path('busca/<int:pk>/update/', views.TermoBuscaUpdate.as_view(), name='busca_update'),
    path('busca/<int:pk>/delete/', views.TermoBuscaDelete.as_view(), name='busca_delete'),

    path('arquivo/', views.arquivo_list, name='arquivo_list'),
    path('arquivo/create/', views.TermoBuscaCreate.as_view(), name='arquivo_create'),
    path('arquivo/<int:pk>/update/', views.TermoBuscaUpdate.as_view(), name='arquivo_update'),
    path('arquivo/<int:pk>/delete/', views.TermoBuscaDelete.as_view(), name='arquivo_delete'),

    path('cadastro/',  views.CadastroView.as_view(), name='cadastro_list'),
    path('cadastro/create/', views.CadastroCreate.as_view(), name='cadastro_create'),
    path('cadastro/<int:pk>/update/', views.CadastroUpdate.as_view(), name='cadastro_update'),
    path('cadastro/<int:pk>/delete/', views.CadastroDelete.as_view(), name='cadastro_delete'),

    path('upload/', views.upload, name='upload'),
    path('index/', views.index, name= 'index'),
    #path('cadastro/json/', views.cadastro_json, name='json'),

    #path('arquivo/files/', views.upload_file, name='upload_file'),
    #url(r'^my/datatable/data/$', views.OrderListJson.as_view(), name='order_list_json'),

    #path('d/', views.cadastroformpage, name='cadastro_create'),

    
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ic_uber/interface/ic_uber/selecting/selecting/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

ic_uber/interface/interface/urls.py
#from django.contrib import admin
#from django.urls import include, path
#from juris import views


#urlpatterns = [
	#path('juris', include('juris.urls')),
    #path('admin/', admin.site.urls),

#]

from django.conf import settings
from django.conf.urls.static import static
import os
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.views.static import serve
from django.contrib.auth import views as auth_views
import django.contrib.auth.urls
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView


# Up two folders to serve "site" content
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')

urlpatterns = [
    path('', TemplateView.as_view(template_name='main.html'), name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('change-password/', auth_views.PasswordChangeView.as_view()),
    path('juris/', include('juris.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': SITE_ROOT, 'show_indexes': True},
        name='site_path'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

ic_uber/interface/ic_uber/interface/juris/forms.py
from django import forms
from juris.fields import ListTextWidget

from django import forms
from juris.models import Cadastro
import base64



from bootstrap_datepicker_plus import DatePickerInput
from django import forms
#from .models import Document

class ProcessoForm(forms.ModelForm):
  #class Meta:
  model = Cadastro
  fields = '__all__'
  #code = base64.b64encode(fields)

   

    #este widget ainda não está funcionando
  widgets = {
        'dataJulgamento': DatePickerInput(format='%d/%m/%Y'), # specify date-frmat
  }



class FormForm(forms.Form):
   char_field_with_list = forms.CharField(required=True)

   def __init__(self, *args, **kwargs):
      _tribunal_list = kwargs.pop('data_list', None)
      super(FormForm, self).__init__(*args, **kwargs)

    # the "name" parameter will allow you to use the same widget more than once in the same
    # form, not setting this parameter differently will cuse all inputs display the
    # same list.
      self.fields['char_field_with_list'].widget = ListTextWidget(data_list=_tribunal_list, name='tribunal_list')


#class EventForm(forms.ModelForm):
    #class Meta:
        #model = Cadastro
        #fields = ['dataJulgamento']
        #widgets = {
            #'dataJulgamento': DatePickerInput(format='%d/%m/%Y'), # specify date-frmat
        #}


#class DocumentForm(forms.Form):
    #docfile = forms.FileField(
        #label='Select a file',
        #help_text='max. 42 megabytes'
    #)

ic_uber/interface/ic_uber/interface/juris/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect, HttpResponse
#from django_datatables_view.base_datatable_view import BaseDatatableView
from django.utils.html import escape


# Imaginary function to handle an uploaded file.

#from somewhere import handle_uploaded_file
from django.core.files.storage import FileSystemStorage
from juris.models import *

from .models import  Cadastro, get_mg_string, get_sp_string
from .forms import ProcessoForm


import json 

from django.http import JsonResponse

# Create your views here.
#def load_varas(request):
    #trt = request.GET.get('tribunal')
    #trtVaras = Varas.objects.filter(tribunal_id=tribunal_id).order_by('name')
    #return render(request, 'hr/dropdown_list_varas.html', {'varas': trtVaras})

class MyView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'registration/login.html')

class ProtectView(LoginRequiredMixin, View) :
    def get(self, request):
        return render(request, 'juris')


class DumpPython(View):
    def get(self, req):
        resp = "<pre>\nUser Data in Python:\n\n"
        resp += "Login url: " + reverse('login') + "\n"
        resp += "Logout url: " + reverse('logout') + "\n\n"
        if req.user.is_authenticated:
            resp += "User: " + req.user.username + "\n"
        else:
            resp += "User is not logged in\n"

        resp += "\n"
        resp += "</pre>\n"
        resp += """<a href="/autos/">Go back</a>"""
        return HttpResponse(resp)

class MainView(LoginRequiredMixin, View):
    def get(self, request):
        emp = Empresa.objects.all().count()
        arq = Arquivo.objects.all().count()
        tbs = TermoBusca.objects.all().count()
        al = Cadastro.objects.all()
        ctx = {'empresa_count': emp, 'cadastro_list': al, 'arquivos_count': arq, 'busca_count': tbs}
        return render(request, 'juris/cadastro_list.html', ctx)

class EmpresaView(LoginRequiredMixin, View):
    def get(self, request):
        empresa = Empresa.objects.all()
        ctx = {'empresa_list': empresa}
        return render(request, 'juris/empresa_list.html', ctx)

class EmpresaCreate(LoginRequiredMixin, CreateView):
    model = Empresa
    fields = '__all__'
    success_url = reverse_lazy('juris:all')

class EmpresaUpdate(LoginRequiredMixin, UpdateView):
    model = Empresa
    fields = '__all__'
    success_url = reverse_lazy('juris:all')

class EmpresaDelete(LoginRequiredMixin, DeleteView):
    model = Empresa
    fields = '__all__'
    success_url = reverse_lazy('juris:all')


class TermoBuscaView(LoginRequiredMixin, View):
    def get(self, request):
        busca = TermoBusca.objects.all()
        ctx = {'busca_list': busca}
        return render(request, 'juris/busca_list.html', ctx)

class TermoBuscaCreate(LoginRequiredMixin, CreateView):
    model = TermoBusca
    fields = '__all__'
    success_url = reverse_lazy('juris:all')

class TermoBuscaUpdate(LoginRequiredMixin, UpdateView):
    model = TermoBusca
    fields = '__all__'
    success_url = reverse_lazy('juris:all')

class TermoBuscaDelete(LoginRequiredMixin, DeleteView):
    model = TermoBusca
    fields = '__all__'
    success_url = reverse_lazy('juris:all')


class ArquivoView(LoginRequiredMixin, View):
    def get(self, request):
        arquivo = Arquivo.objects.all()
        ctx = {'arquivo_list': arquivo}
        return render(request, 'juris/arquivo_list.html', ctx)

class TermoBuscaCreate(LoginRequiredMixin, CreateView):
    model = Arquivo
    fields = '__all__'
    success_url = reverse_lazy('juris:all')

class TermoBuscaUpdate(LoginRequiredMixin, UpdateView):
    model = Arquivo
    fields = '__all__'
    success_url = reverse_lazy('juris:all')

class TermoBuscaDelete(LoginRequiredMixin, DeleteView):
    model = Arquivo
    fields = '__all__'
    success_url = reverse_lazy('juris:all')

# We use reverse_lazy() because we are in "constructor attribute" code
# that is run before urls.py is completely loaded]]

class CadastroView(LoginRequiredMixin, View):
    def get(self, request):
        cadastro = Cadastro.objects.all()
        ctx = {'cadastro_list': cadastro}
        return render(request, 'juris/cadastro_list.html', ctx)

class CadastroCreate(CreateView):
    model = Cadastro
    fields = '__all__'
    success_url = reverse_lazy('juris:index')

class CadastroUpdate(LoginRequiredMixin, UpdateView):
    model = Cadastro
    fields = '__all__'
    success_url = reverse_lazy('juris:all')

class CadastroDelete(LoginRequiredMixin, DeleteView):
    model = Cadastro
    fields = '__all__'
    success_url = reverse_lazy('juris:all')

def post_create(request):
    form = ProcessoForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commin=False)
        instance.save()
        messages.success(request, "Successfully Created!")
        return HttpResponseRedirect (instance.get_absolute_url())
    context = {
        "form": form,
    }
    return render(request, "cadastro_form.html", context)

def post_update(request, id=None):
    instance = get_object_or_404(ProcessoForm, id=id)
    form = PostForm(request.POST or None, request.FILES or None, instance = instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "<a href='#'Item</a> Saved", extra_tags='html_save')
        return HttpResponseRedirect(instance.get_absolute_url())

        context = {
        "processo" : instance.numero,
        "instance": instance,
        "form": form,
        }

        return render(request, "cadastro_form.html", context)


def post_delete(request, id=None):
    instance = get_object_or_404(ProcessoForm, id=id)
    instance.delete()
    messages.success(request, "Successfully deleted!")
    return redirect("juris:cadastro_list")



#def upload_file(request):
    #if request.method == 'POST':
        #form = Processo(request.POST, request.FILES)
        #if form.is_valid():
            #handle_uploaded_file(request.FILES['docfile'])
            #return HttpResponseRedirect('/success/url/')
    #else:
        #form = Processo()
    #return render(request, 'juris:create', {'form': form})
def index(request):
    context ={}
    cadastro_list = Cadastro.objects.all()
    context['cadastro_list'] = cadastro_list
    return render(request, 'index.html', context)

def Main(request):
    return render(request, 'juris: main.html')

#==========


def upload(request):
    context = {}
    if request.method == 'POST':
        uploaded_file = request.FILES["document"]
        fs = FileSystemStorage()
        name = fs.save(uploaded_file.name, uploaded_file)
        context['url'] = fs.url(name)
    return render(request, 'juris/upload.html', context)



def arquivo_list(request):
    arquivos = Cadastro.objects.all()
    return render(request, 'juris/arquivo_list.html', {
        'arquivos': arquivos
        })


#def Upload_Arquivo(request):
        #if request.method == "POST":
            #file = Processo(request.POST, request.FILES)
            #if form.is_valid():
                #form.save()
                #return redirect('arquivo_list')
        #else:
            #file = Processo()
        #return render(request, 'juris/upload_file.html', {
        #'form': form 

       # })

#================= PROJECT TO SELECT =========================


def country_form(request):
    # instead of hardcoding a list you could make a query of a model, as long as
    # it has a __str__() method you should be able to display it.
    tribunal_list = TRIBUNAIS_TRABALHISTAS
    form = FormForm(data_list=tribunal_list)

    return render(request, 'juris/tribunal_list.html', {
        'form': form
    })


#def cadastro_json(request):
    #cadastros = Cadastro.objects.all()
    #data = [cadastro.to_dict_json() for cadastro in cadastros]
    #response={'data':data}
    #return JsonResponse(response)


# References

# https://docs.djangoproject.com/en/3.0/ref/class-based-views/generic-editing/#createview

#class OrderListJson(BaseDatatableView):
        # The model we're going to show
    #model = Cadastro

        # define the columns that will be returned
    #columns = ['pesquisa', 'numero', 'poloPassivo', 'tipoProcesso', 'tribunal', 'estado', 'tipoDecisao', 'dataJulgamento', 'vinculoEmpregaticio']


        # define column names that will be used in sorting
        # order is important and should be same as order of columns
        # displayed by datatables. For non sortable columns use empty
        # value like ''
        #order_columns = ['number', 'user', 'state', '', '']

        # set max limit of records returned, this is used to protect our site if someone tries to attack our site
        # and make it return huge amount of data
    #max_display_length = 500

        #def render_column(self, row, column):
            # We want to render user as a custom column
            #if column == 'user':
                # escape HTML for security reasons
                #return escape('{0} {1}'.format(row.customer_firstname, row.customer_lastname))
            #else:
                #return super(OrderListJson, self).render_column(row, column)

    #def filter_queryset(self, qs):
            # use parameters passed in GET request to filter queryset

            # simple example:
        #search = self.request.GET.get('search[value]', None)
        ##if search:
            #qs = qs.filter(number__istartswith=search)

            # more advanced example using extra parameters
        #filter_estado = self.request.GET.get('estado', None)
        #filter_empresa = self.request.GET.get('poloPassivo', None)

ic_uber/interface/ic_uber/interface/juris/templates/main.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Uberization in Brazil</title>
        <link rel="icon" type="image/x-icon" href="assets/img/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="{% static 'https://use.fontawesome.com/releases/v5.15.1/js/all.js'%}" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="{% static 'https://fonts.googleapis.com/css?family=Varela+Round' %}" rel="stylesheet" />
        <link href="{% static 'https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i' %}" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'juris/css/styles.css' %}" rel="stylesheet" />
      <link rel="stylesheet" href="global-styles.css">
  <style>
    .fullclick {
      margin: 1em 0;
      padding: 0;
      max-width: 30em;
    }
    .fullclick li {
      list-style: none;
      margin: 1em 0;
      padding: 10px 5px;
      background: #629c92;
      position: relative;
    }
    .fullclick a.main {
      color: white;
      text-align: right;
      display: block;
      z-index: 1;
    }
    .fullclick li a.main::after {
      position: absolute;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      content: ' ';
    }

    .center {
      margin: auto;
      width: 60%;
      height: 50%;
      /*border: 3px solid #73AD21;*/
      /*background: #629c92;*/
      color: gray;
      padding: 0px;
    }

  </style>
    </head>
{% block content %}
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger" href="#page-top">Top page</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Options
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#about">About</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#projects">Analysis</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'juris:login' %}">Login</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'juris:cadastro_create' %}">Database Manipulation</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#signup">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        <header class="masthead">
            <div class="container d-flex h-100 align-items-center">
                <div class="mx-auto text-center">
                    <h1 class="mx-auto my-0 text-uppercase">Uberisation in Brazil</h1>
                    <h2 class="text-white-50 mx-auto mt-2 mb-5">Mapping the legal understanding and response to the emerging morphologies and organization of labor</h2>
                    <a class="btn btn-primary js-scroll-trigger" href="{% url 'juris:cadastro_create' %}">Get Started</a>
                </div>
            </div>
        </header>
        <!-- About-->
        <section class="about-section text-center" id="about">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 mx-auto">
                        <h2 class="text-white mb-4">Research</h2>
                        <p class="text-white-50">
                            Uberization, Gig Economy, Gig Work, Precarization, Informal Labor. All these terms, and a lot more, are used to describe in order to trying to grasp the complexity and heterogeneous phenomena in the currently organization of work in the global/digital market of today.
                            How we can approach that?
                            Legal frame of this question is enough? We believe not, but still, legal understand of these contemporary issues is essencial to think how to regulate these kind of works around the globe.
                        </p>
                    </div>
                     <!-- <h1> Explore </h1>  -->
                      <div class="center" >
                        <p>
                          <h4>Archives of the Research Project</h4>
                         
                            Here you will encounter our research project and other archives that are our reading to conduct the project itself.  
                          
                          <a href="{% url 'juris:cadastro_create' %}" class="main">More info.</a>
                        </p>
                        <p>
                          <h4>Brazilian Jurisprudence Database</h4>
                          
                            Here you will find the judicial cases against companies like Uber, iFood, Loggi, Natura, 99 Tecnologia and others that is part of our sample to analyse the understandin f the phenomena called "uberisation of work".
                        
                          <a href="{% url 'juris:index' %}" class="main">More info.</a>
                        </p>
                            <p>
                          <h4>Our current thoughts </h4>
                         
                          In this space you can read our thoughts and the status of the current research. 
                          Here we put also our favorite podcasts, readings, documents, news, etc.
                         
                          <a href="{% url 'juris:arquivo_list' %}" class="main">Explore more here</a>
                        </p>
                      </div>



                </div>
                <!--<img class="img-fluid" src="{% static 'juris/giphy.gif'%}" alt="" /> --> 
            </div>
        </section>


        <section class="projects-section bg-light" id="projects">
            <div class="container">
                <!-- Featured Project Row-->
                <div class="row align-items-center no-gutters mb-4 mb-lg-5">
                    <div class="col-xl-8 col-lg-7"><img class="img-fluid mb-3 mb-lg-0" src="{% static 'assets/img/bg-masthead.jpg' %}" alt="" /></div>
                    <div class="col-xl-4 col-lg-5">
                        <div class="featured-text text-center text-lg-left">
                            <h4>Levels of </h4>
                            <p class="text-black-50 mb-0">Due to the multidimensional characteristics of the contemporary labor organization that we generally refer as 'uberization', it's very important to divide the levels of analysis to demonstrate our research and understading of these questions.</p>
                        </div>
                    </div>
                </div>
                <!-- Project One Row-->
                <div class="row justify-content-center no-gutters mb-5 mb-lg-0">
                    <div class="col-lg-6"><img class="img-fluid" src="{% static 'assets/img/demo-image-01.jpg' %}" alt="" /></div>
                    <div class="col-lg-6">
                        <div class="bg-black text-center h-100 project">
                            <div class="d-flex h-100">
                                <div class="project-text w-100 my-auto text-center text-lg-left">
                                    <h4 class="text-white">Digital Law</h4>
                                    <p class="mb-0 text-white-50">One level of analysis </p>
                                    <hr class="d-none d-lg-block mb-0 ml-0" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Project Two Row-->
                <div class="row justify-content-center no-gutters">
                    <div class="col-lg-6"><img class="img-fluid" src="{% static 'assets/img/demo-image-02.jpg' %}" alt="" /></div>
                    <div class="col-lg-6 order-lg-first">
                        <div class="bg-black text-center h-100 project">
                            <div class="d-flex h-100">
                                <div class="project-text w-100 my-auto text-center text-lg-right">
                                    <h4 class="text-white">Intersections with the Theory of Law</h4>
                                    <p class="mb-0 text-white-50">Digital law and Computational Law</p>
                                    <hr class="d-none d-lg-block mb-0 mr-0" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Signup-->
        <section class="signup-section" id="signup">
            <div class="container">
                <div class="row">
                    <div class="col-md-10 col-lg-8 mx-auto text-center">
                        <i class="far fa-paper-plane fa-2x mb-2 text-white"></i>
                        <h2 class="text-white mb-5">Subscribe to receive updates!</h2>
                        <form class="form-inline d-flex">
                            <input class="form-control flex-fill mr-0 mr-sm-2 mb-3 mb-sm-0" id="inputEmail" type="email" placeholder="Enter email address..." />
                            <button class="btn btn-primary mx-auto" type="submit">Subscribe</button>
                        </form>
                    </div>
                </div>
            </div>
        </section>

        <!-- Contact-->
        <section class="contact-section bg-black">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 mb-3 mb-md-0">
                        <div class="card py-4 h-100">
                            <div class="card-body text-center">
                                <i class="fas fa-map-marked-alt text-primary mb-2"></i>
                                <h4 class="text-uppercase m-0">Location</h4>
                                <hr class="my-4" />
                                <div class="small text-black-50">Limeira, São Paulo - Brasil</div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 mb-3 mb-md-0">
                        <div class="card py-4 h-100">
                            <div class="card-body text-center">
                                <i class="fas fa-envelope text-primary mb-2"></i>
                                <h4 class="text-uppercase m-0">Email</h4>
                                <hr class="my-4" />
                                <div class="small text-black-50"><a href="#!">krodrigues.firmino2@gmail.com</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 mb-3 mb-md-0">
                        <div class="card py-4 h-100">
                            <div class="card-body text-center">
                                <i class="fas fa-mobile-alt text-primary mb-2"></i>
                                <h4 class="text-uppercase m-0">Other Informations</h4>
                                <hr class="my-4" />
                                <div class="small text-black-50">Pesquisa desenvolvida por: Helora Maria Machado da Cunha e  
                                Karoline Rodrigues Firmino;
            
                                Orientador: Ricardo Antonio Bittar Hajel Filho

                                <p>Instituição: Universidade Paulista (UNIP) - Campus Limeira /

                               Apoio: Santander Universidades </p>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="social d-flex justify-content-center">
                    <a class="mx-2" href="{% static '#!'%}"><i class="fab fa-twitter"></i></a>
                    <a class="mx-2" href="{% static '#!'%}"><i class="fab fa-facebook-f"></i></a>
                    <a class="mx-2" href="{% static '#!'%}"><i class="fab fa-github"></i></a>
                </div>
            </div>
{% endblock %}
        </section>
        <!-- Footer-->
        <footer class="footer bg-black small text-center text-white-50"><div class="container">Copyright © Proudly produced by Karoline Rodrigues Firmino, 2021</div></footer>
        <!-- Bootstrap core JS-->
        <script src="{% static 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js' %}"></script>
        <script src="{% static 'https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js'%}"></script>
        <!-- Third party plugin JS-->
        <script src="{% static 'https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js' %}"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
          <script src="donav.js"></script>

    </body>
</html>

ic_uber/interface/ic_uber/interface/juris/templates/nav.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href=" {% url 'juris:index' %}">Em construção</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'juris:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'juris:cadastro_create' %}">Cadadastrar - Banco de Dados</a>
      </li>
      <!-- <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li> -->
    </ul>
  </div>
</nav>