ic_uber/interface/ic_uber/interface/juris/urls.py
from django.urls import path, include
from . import views 
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
import juris.views
from django.conf import settings
import os
from django.conf.urls import  url

# https://docs.djangoproject.com/en/3.0/topics/http/urls/
app_name = 'juris'

urlpatterns = [

    path('', views.MainView.as_view(), name='all'),
    #path('accounts/', views.MyView.as_view(), name='login'),
    path('protect', views.ProtectView.as_view(), name='protect'),
    path('python', views.DumpPython.as_view(), name='python'),

    path('empresa/', views.EmpresaView.as_view(), name='empresa_list'),
    path('empresa/create/', views.EmpresaCreate.as_view(), name='empresa_create'),
    path('empresa/<int:pk>/update/', views.EmpresaUpdate.as_view(), name='empresa_update'),
    path('empresa/<int:pk>/delete/', views.EmpresaDelete.as_view(), name='empresa_delete'),

    path('busca/', views.TermoBuscaView.as_view(), name='busca_list'),
    path('busca/create/', views.TermoBuscaCreate.as_view(), name='busca_create'),
    path('busca/<int:pk>/update/', views.TermoBuscaUpdate.as_view(), name='busca_update'),
    path('busca/<int:pk>/delete/', views.TermoBuscaDelete.as_view(), name='busca_delete'),

    path('arquivo/', views.arquivo_list, name='arquivo_list'),
    path('arquivo/create/', views.TermoBuscaCreate.as_view(), name='arquivo_create'),
    path('arquivo/<int:pk>/update/', views.TermoBuscaUpdate.as_view(), name='arquivo_update'),
    path('arquivo/<int:pk>/delete/', views.TermoBuscaDelete.as_view(), name='arquivo_delete'),

    path('cadastro/',  views.CadastroView.as_view(), name='cadastro_list'),
    path('cadastro/create/', views.CadastroCreate.as_view(), name='cadastro_create'),
    path('cadastro/<int:pk>/update/', views.CadastroUpdate.as_view(), name='cadastro_update'),
    path('cadastro/<int:pk>/delete/', views.CadastroDelete.as_view(), name='cadastro_delete'),

    path('upload/', views.upload, name='upload'),
    path('index/', views.index, name= 'index'),
    #path('cadastro/json/', views.cadastro_json, name='json'),

    #path('arquivo/files/', views.upload_file, name='upload_file'),
    #url(r'^my/datatable/data/$', views.OrderListJson.as_view(), name='order_list_json'),

    #path('d/', views.cadastroformpage, name='cadastro_create'),

    
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ic_uber/interface/ic_uber/selecting/selecting/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

ic_uber/interface/interface/urls.py
#from django.contrib import admin
#from django.urls import include, path
#from juris import views


#urlpatterns = [
	#path('juris', include('juris.urls')),
    #path('admin/', admin.site.urls),

#]

from django.conf import settings
from django.conf.urls.static import static
import os
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.views.static import serve
from django.contrib.auth import views as auth_views
import django.contrib.auth.urls
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView


# Up two folders to serve "site" content
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')

urlpatterns = [
    path('', TemplateView.as_view(template_name='main.html'), name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('change-password/', auth_views.PasswordChangeView.as_view()),
    path('juris/', include('juris.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': SITE_ROOT, 'show_indexes': True},
        name='site_path'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

ic_uber/interface/ic_uber/interface/juris/forms.py
from django import forms
from juris.fields import ListTextWidget

from django import forms
from juris.models import Cadastro
import base64



from bootstrap_datepicker_plus import DatePickerInput
from django import forms
#from .models import Document

class ProcessoForm(forms.ModelForm):
  #class Meta:
  model = Cadastro
  fields = '__all__'
  #code = base64.b64encode(fields)

   

    #este widget ainda não está funcionando
  widgets = {
        'dataJulgamento': DatePickerInput(format='%d/%m/%Y'), # specify date-frmat
  }



class FormForm(forms.Form):
   char_field_with_list = forms.CharField(required=True)

   def __init__(self, *args, **kwargs):
      _tribunal_list = kwargs.pop('data_list', None)
      super(FormForm, self).__init__(*args, **kwargs)

    # the "name" parameter will allow you to use the same widget more than once in the same
    # form, not setting this parameter differently will cuse all inputs display the
    # same list.
      self.fields['char_field_with_list'].widget = ListTextWidget(data_list=_tribunal_list, name='tribunal_list')


#class EventForm(forms.ModelForm):
    #class Meta:
        #model = Cadastro
        #fields = ['dataJulgamento']
        #widgets = {
            #'dataJulgamento': DatePickerInput(format='%d/%m/%Y'), # specify date-frmat
        #}


#class DocumentForm(forms.Form):
    #docfile = forms.FileField(
        #label='Select a file',
        #help_text='max. 42 megabytes'
    #)

ic_uber/interface/ic_uber/interface/juris/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect, HttpResponse
#from django_datatables_view.base_datatable_view import BaseDatatableView
from django.utils.html import escape


# Imaginary function to handle an uploaded file.

#from somewhere import handle_uploaded_file
from django.core.files.storage import FileSystemStorage
from juris.models import *

from .models import  Cadastro, get_mg_string, get_sp_string
from .forms import ProcessoForm


import json 

from django.http import JsonResponse

# Create your views here.
#def load_varas(request):
    #trt = request.GET.get('tribunal')
    #trtVaras = Varas.objects.filter(tribunal_id=tribunal_id).order_by('name')
    #return render(request, 'hr/dropdown_list_varas.html', {'varas': trtVaras})

class MyView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'registration/login.html')

class ProtectView(LoginRequiredMixin, View) :
    def get(self, request):
        return render(request, 'juris')


class DumpPython(View):
    def get(self, req):
        resp = "<pre>\nUser Data in Python:\n\n"
        resp += "Login url: " + reverse('login') + "\n"
        resp += "Logout url: " + reverse('logout') + "\n\n"
        if req.user.is_authenticated:
            resp += "User: " + req.user.username + "\n"
        else:
            resp += "User is not logged in\n"

        resp += "\n"
        resp += "</pre>\n"
        resp += """<a href="/autos/">Go back</a>"""
        return HttpResponse(resp)

class MainView(LoginRequiredMixin, View):
    def get(self, request):
        emp = Empresa.objects.all().count()
        arq = Arquivo.objects.all().count()
        tbs = TermoBusca.objects.all().count()
        al = Cadastro.objects.all()
        ctx = {'empresa_count': emp, 'cadastro_list': al, 'arquivos_count': arq, 'busca_count': tbs}
        return render(request, 'juris/cadastro_list.html', ctx)

class EmpresaView(LoginRequiredMixin, View):
    def get(self, request):
        empresa = Empresa.objects.all()
        ctx = {'empresa_list': empresa}
        return render(request, 'juris/empresa_list.html', ctx)

class EmpresaCreate(LoginRequiredMixin, CreateView):
    model = Empresa
    fields = '__all__'
    success_url = reverse_lazy('juris:all')

class EmpresaUpdate(LoginRequiredMixin, UpdateView):
    model = Empresa
    fields = '__all__'
    success_url = reverse_lazy('juris:all')

class EmpresaDelete(LoginRequiredMixin, DeleteView):
    model = Empresa
    fields = '__all__'
    success_url = reverse_lazy('juris:all')


class TermoBuscaView(LoginRequiredMixin, View):
    def get(self, request):
        busca = TermoBusca.objects.all()
        ctx = {'busca_list': busca}
        return render(request, 'juris/busca_list.html', ctx)

class TermoBuscaCreate(LoginRequiredMixin, CreateView):
    model = TermoBusca
    fields = '__all__'
    success_url = reverse_lazy('juris:all')

class TermoBuscaUpdate(LoginRequiredMixin, UpdateView):
    model = TermoBusca
    fields = '__all__'
    success_url = reverse_lazy('juris:all')

class TermoBuscaDelete(LoginRequiredMixin, DeleteView):
    model = TermoBusca
    fields = '__all__'
    success_url = reverse_lazy('juris:all')


class ArquivoView(LoginRequiredMixin, View):
    def get(self, request):
        arquivo = Arquivo.objects.all()
        ctx = {'arquivo_list': arquivo}
        return render(request, 'juris/arquivo_list.html', ctx)

class TermoBuscaCreate(LoginRequiredMixin, CreateView):
    model = Arquivo
    fields = '__all__'
    success_url = reverse_lazy('juris:all')

class TermoBuscaUpdate(LoginRequiredMixin, UpdateView):
    model = Arquivo
    fields = '__all__'
    success_url = reverse_lazy('juris:all')

class TermoBuscaDelete(LoginRequiredMixin, DeleteView):
    model = Arquivo
    fields = '__all__'
    success_url = reverse_lazy('juris:all')

# We use reverse_lazy() because we are in "constructor attribute" code
# that is run before urls.py is completely loaded]]

class CadastroView(LoginRequiredMixin, View):
    def get(self, request):
        cadastro = Cadastro.objects.all()
        ctx = {'cadastro_list': cadastro}
        return render(request, 'juris/cadastro_list.html', ctx)

class CadastroCreate(CreateView):
    model = Cadastro
    fields = '__all__'
    success_url = reverse_lazy('juris:index')

class CadastroUpdate(LoginRequiredMixin, UpdateView):
    model = Cadastro
    fields = '__all__'
    success_url = reverse_lazy('juris:all')

class CadastroDelete(LoginRequiredMixin, DeleteView):
    model = Cadastro
    fields = '__all__'
    success_url = reverse_lazy('juris:all')

def post_create(request):
    form = ProcessoForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commin=False)
        instance.save()
        messages.success(request, "Successfully Created!")
        return HttpResponseRedirect (instance.get_absolute_url())
    context = {
        "form": form,
    }
    return render(request, "cadastro_form.html", context)

def post_update(request, id=None):
    instance = get_object_or_404(ProcessoForm, id=id)
    form = PostForm(request.POST or None, request.FILES or None, instance = instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "<a href='#'Item</a> Saved", extra_tags='html_save')
        return HttpResponseRedirect(instance.get_absolute_url())

        context = {
        "processo" : instance.numero,
        "instance": instance,
        "form": form,
        }

        return render(request, "cadastro_form.html", context)


def post_delete(request, id=None):
    instance = get_object_or_404(ProcessoForm, id=id)
    instance.delete()
    messages.success(request, "Successfully deleted!")
    return redirect("juris:cadastro_list")



#def upload_file(request):
    #if request.method == 'POST':
        #form = Processo(request.POST, request.FILES)
        #if form.is_valid():
            #handle_uploaded_file(request.FILES['docfile'])
            #return HttpResponseRedirect('/success/url/')
    #else:
        #form = Processo()
    #return render(request, 'juris:create', {'form': form})
def index(request):
    context ={}
    cadastro_list = Cadastro.objects.all()
    context['cadastro_list'] = cadastro_list
    return render(request, 'index.html', context)

def Main(request):
    return render(request, 'juris: main.html')

#==========


def upload(request):
    context = {}
    if request.method == 'POST':
        uploaded_file = request.FILES["document"]
        fs = FileSystemStorage()
        name = fs.save(uploaded_file.name, uploaded_file)
        context['url'] = fs.url(name)
    return render(request, 'juris/upload.html', context)



def arquivo_list(request):
    arquivos = Cadastro.objects.all()
    return render(request, 'juris/arquivo_list.html', {
        'arquivos': arquivos
        })


#def Upload_Arquivo(request):
        #if request.method == "POST":
            #file = Processo(request.POST, request.FILES)
            #if form.is_valid():
                #form.save()
                #return redirect('arquivo_list')
        #else:
            #file = Processo()
        #return render(request, 'juris/upload_file.html', {
        #'form': form 

       # })

#================= PROJECT TO SELECT =========================


def country_form(request):
    # instead of hardcoding a list you could make a query of a model, as long as
    # it has a __str__() method you should be able to display it.
    tribunal_list = TRIBUNAIS_TRABALHISTAS
    form = FormForm(data_list=tribunal_list)

    return render(request, 'juris/tribunal_list.html', {
        'form': form
    })


#def cadastro_json(request):
    #cadastros = Cadastro.objects.all()
    #data = [cadastro.to_dict_json() for cadastro in cadastros]
    #response={'data':data}
    #return JsonResponse(response)


# References

# https://docs.djangoproject.com/en/3.0/ref/class-based-views/generic-editing/#createview

#class OrderListJson(BaseDatatableView):
        # The model we're going to show
    #model = Cadastro

        # define the columns that will be returned
    #columns = ['pesquisa', 'numero', 'poloPassivo', 'tipoProcesso', 'tribunal', 'estado', 'tipoDecisao', 'dataJulgamento', 'vinculoEmpregaticio']


        # define column names that will be used in sorting
        # order is important and should be same as order of columns
        # displayed by datatables. For non sortable columns use empty
        # value like ''
        #order_columns = ['number', 'user', 'state', '', '']

        # set max limit of records returned, this is used to protect our site if someone tries to attack our site
        # and make it return huge amount of data
    #max_display_length = 500

        #def render_column(self, row, column):
            # We want to render user as a custom column
            #if column == 'user':
                # escape HTML for security reasons
                #return escape('{0} {1}'.format(row.customer_firstname, row.customer_lastname))
            #else:
                #return super(OrderListJson, self).render_column(row, column)

    #def filter_queryset(self, qs):
            # use parameters passed in GET request to filter queryset

            # simple example:
        #search = self.request.GET.get('search[value]', None)
        ##if search:
            #qs = qs.filter(number__istartswith=search)

            # more advanced example using extra parameters
        #filter_estado = self.request.GET.get('estado', None)
        #filter_empresa = self.request.GET.get('poloPassivo', None)

ic_uber/interface/ic_uber/interface/juris/templates/juris/arquivo_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>Arquivo - Lista</h1>
  {% if busca_list %}
  <ul>
    {% for arquivo in arquivos %}
      <li>
          {{ arquivo.id }}
          {{ arquivo.numero }}
          {{ arquivo.tribunal}}
          {{ arquivo.arquivo }}
         (<a href="{% url 'juris:arquivo_update' arquivo.id %}">Atualizar</a> |
          <a href="{% url 'juris:arquivo_delete' arquivo.id %}">Deletar</a>)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p> Não há arquivos nesta biblioteca.</p>
  {% endif %}
  <p><a href="{% url 'juris:arquivo_create' %}">Adicione um arquivo</a></p>
  <p>
    <a href="{% url 'juris:all' %}">Voltar para Home</a>
  </p>
{% endblock %}

ic_uber/interface/ic_uber/interface/juris/templates/juris/busca_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'juris:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

ic_uber/interface/ic_uber/interface/juris/templates/juris/busca_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>Termo de Busca - Lista</h1>
  {% if busca_list %}
  <ul>
    {% for busca in busca_list %}
      <li>
          {{ busca.name }}
         (<a href="{% url 'juris:termobusca_update' termobusca.id %}">Atualizar</a> |
          <a href="{% url 'juris:termobusca_delete' termobusca.id %}">Deletar</a>)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p> Não há termos de busca nessa biblioteca.</p>
  {% endif %}
  <p><a href="{% url 'juris:termobusca_create' %}">Adicione um termo de busca/pesquisa</a></p>
  <p>
    <a href="{% url 'juris:all' %}">Voltar para Home</a>
  </p>
{% endblock %}

ic_uber/interface/ic_uber/interface/juris/templates/juris/cadastro_confirm_delete.html
{% extends "base_bootstrap.html" %}
{% load static %}

<head>
	 <link href="{% static 'juris/css/styles.css' %}" rel="stylesheet" />
</head>
{% block content %}

<h1>Deletar Cadastros</h1>

<p>Você tem certeza que quer excluir o cadastro: {{ cadastro }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Sim, deletar.">
  <input type="submit" onclick="window.location='{% url 'juris:all' %}' ; return false;" value="Cancel">
</form>

{% endblock %}

ic_uber/interface/ic_uber/interface/juris/templates/juris/cadastro_form.html
{% extends "base.html" %}


<!DOCTYPE html>
<html lang="en">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<head>
    <meta charset="UTF-8">
    <title> Legal Cases - Registerin in the database</title>




<style>
.content {
  max-width: 500px;
  margin: auto;
}
</style>

</head>

{% block content %}
<body>
<div class="content">
  <form method="post" id="Processo" action="" enctype="multipart/form-data">
    {% csrf_token %}
    
    {{ form.as_p}}
    {{ cadastroform.as_p}}

    

			<!--{% if url %}
			<p> Upload file: <a href = "{{url}}">{{url}}</a></p>
			{% endif %} -->

    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'juris:index' %}' ; return false;" value="Cancel">

    <!-- {{datatable.render}}
 -->   

      <script>

          $(document).ready(function(){


            $('#id_vara').empty();

            var spString = JSON.parse('{{json_sp_string | escapejs}}');
            var mgString = JSON.parse('{{json_mg_string | escapejs}}');


          $('#id_tribunal').on('change', function(){

            var tribunal = $('#id_tribunal').val();



            if(tribunal== "2ª Região - São Paulo/SP"){

              $('#id_vara').empty();

              var lenght = spString.lenght;
              var i;
              for(i=0; i < lenght; i++){

                vara = spString[i];
                $('#id_vara').append(

                             `
                            <option value="${vara}">
                                ${vara}
                            </option>

                            `
                          );

                    }

                }
              

              else if(tribunal == '3ª Região - Belo Horizonte/MG'){

                    $('#id_vara').empty();

                  var length = mgStrings.length;
                  var i;
                  for(i=0; i < length; i++){

                        vara = mgStrings[i];
                        $('#id_vara').append(

                            `
                            <option value="${vara}">
                                ${vara}
                            </option>
                            `

                        );

                    }

                }

                else{

                    $('#id_vara').empty();

                }

          });
   });

        </script>
  </form>

</body>


</html>

{% endblock %}

ic_uber/interface/ic_uber/interface/juris/templates/juris/cadastro_list.html
<!DOCTYPE html>
<html>
<head>
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}

.myself .property{
  width:30%;
  display:inline-block;
  box-sizing:border-box;
  text-align:right;
  }

.myself .value{
  text-align:left;
  padding-left:10px;
  width:70%;
  display:inline-block;
  box-sizing:border-box;
  }

</style>
</head>

{% block content %}
  <h1>Cadastro - Lista</h1>
  {% if cadastro_list %}
  <ul>
    {% for cadastro in cadastro_list %}
      <li>
        <table id="mytable">
  <colgroup>
    <col span="5" >

            <tr>
              <div class= property> <th>id </th> </div>
              <div class= property> <th>Número do processo </th></div>
              <div class= property> <th> Empresa </th></div>
              <div class= property> <th> Vínculo Empregatício </th></div>
              <div class= property> <th> Estado </th></div>
            </tr>
                <tr>
                <div class= value><td> {{ cadastro.id }} </td></div>
                <div class= value> <td>{{ cadastro.numero }} </td></div>
                <div class= value> <td> {{ cadastro.poloPassivo }}  </td></div>
                <div class= value> <td> {{ cadastro.vinculoEmpregaticio}} </td></div>
                <div class= value> <td> {{ cadastro.estado }} </td></div>
              </tr>
 
         (<a href="{% url 'juris:cadastro_update' cadastro.id %}">Atualizar</a> |
          <a href="{% url 'juris:cadastro_delete' cadastro.id %}">Deletar</a>)
  </colgroup>
        </table>
      </li>

    {% endfor %}
  </ul>
  {% else %}
    <p> Não há cadastros nesta biblioteca.</p>
  {% endif %}
  <p><a href="{% url 'juris:cadastro_create' %}">Realize um Cadastro</a></p>
  <!-- <p>
    <a href="{% url 'juris:empresa_list' %}">Voltar para Home</a>
  </p> -->
{% endblock %}



</body>
</html>

ic_uber/interface/ic_uber/interface/juris/templates/juris/empresa_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Deletar Empresa</h1>

<p>Você tem certeza que quer excluir a empresa: {{ empresa }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Sim, delete.">
  <input type="submit" onclick="window.location='{% url 'juris:all' %}' ; return false;" value="Cancel">
</form>

{% endblock %}

ic_uber/interface/ic_uber/interface/juris/templates/juris/empresa_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'juris:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

ic_uber/interface/ic_uber/interface/juris/templates/juris/empresa_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>Empresa - Lista</h1>
  {% if empresa_list %}
  <ul>
    {% for empresa in empresa_list %}
      <li>
          {{ empresa.name }}
         (<a href="{% url 'juris:empresa_update' empresa.id %}">Atualizar</a> |
          <a href="{% url 'juris:empresa_delete' empresa.id %}">Deletar</a>)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p> Não há empresas nessa biblioteca.</p>
  {% endif %}
  <p><a href="{% url 'juris:empresa_create' %}">Adicione uma empresa</a></p>
  <p>
    <a href="{% url 'juris:all' %}">Voltar para Home</a>
  </p>
{% endblock %}

ic_uber/interface/ic_uber/interface/juris/templates/juris/test1.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🗂</text></svg>">
  <title>Full list click example</title>
  <link rel="stylesheet" href="global-styles.css">
  <style>
    .fullclick {
      margin: 1em 0;
      padding: 0;
      max-width: 30em;
    }
    .fullclick li {
      list-style: none;
      margin: 1em 0;
      padding: 20px 10px;
      background: #2b2b2b;
      position: relative;
      transition: 400ms;
    }
   .fullclick p a {
      color: lime;
      z-index: 2;
      position: relative;
    }
    .fullclick a.main {
      color: #85baff;
      text-align: right;
      display: block;
      z-index: 1;
    }
    .fullclick li a.main::after {
      position: absolute;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      content: ' ';
    }
    .fullclick:hover a.main, 
    .fullclick:focus-within a.main {
      color: #cfe4ff;
    }
    .fullclick li button {
      z-index: 2;
      position: absolute;
      top: 5px;
      right: 5px;
      opacity: 0;
      transition: 400ms;
      border: none;
      color: #fff;
      background: #333;
    }
    .fullclick li:hover button, 
    .fullclick li:focus-within button {
      opacity: 1;
    }
    .fullclick li:hover, .fullclick li:focus-within {
      background:#484848;
      box-shadow: 0px 3px 6px #000;
    }
  </style>
</head>
<body>

  <h1>Animals that make me happy</h1>
  <ul class="fullclick">
    <li>
      <h2>Dogs</h2>
      <p>
        Dogs are excellent, and good people. If want to browse dogs
        by breed, check <a href="https://codepo8.github.io/dog-browser/">
        The dog browser</a>. Almost all dogs are good boys and girls. 
      </p>
      <a href="dogs.html" class="main">More dog news</a>
      <button title="click to close" aria-label="click to close">x</button>
    </li>
    <li>
      <h2>Wombats</h2>
      <p>
        Wombats are cute as buttons and digging machines. They look always
        chill and jolly, but aren't a good idea to keep in the house.
      </p>
      <a href="wombat.html" class="main">More wombat info</a>
      <button title="click to close" aria-label="click to close">x</button>
    </li>
  </ul>
  <script src="donav.js"></script>
</body>
</html>

ic_uber/interface/ic_uber/interface/juris/templates/juris/upload.html
{% load static %}
<head>
	 <link href="{% static 'juris/css/styles.css' %}" rel="stylesheet" />
</head>


{% block content %}
	<h2> Upload </h2>

	<form method ="post" enctype="multipart/form-data">
		{% csrf_token %}
		<input type="file" name="document">
		<button type="submit"> Upload file </button>
	</form>
	{% if url %}
	<p> Upload file: <a href = "{{url}}">{{url}}</a></p>
	{% endif %}


{% endblock %} 